// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upbdxfrxwgzfrahiuqoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwYmR4ZnJ4d2d6ZnJhaGl1cW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNTU0NDIsImV4cCI6MjA2NjczMTQ0Mn0.VoB-Ej7OgR4OxigynBAuTaspqCay_m3WvnqEsxQutgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});